services:
  db:
    image: postgres:16
    container_name: minibank_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minibank
    ports:
      - "5432:5432"
